name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: corepack prepare pnpm@latest --activate
      - run: pnpm install
      # Debugging step to verify secrets are set
      - run: echo "SUPABASE_URL is set" && echo $SUPABASE_URL | wc -c
      - run: echo "SUPABASE_KEY is set" && echo $SUPABASE_KEY | wc -c
      # Build the project
      - run: pnpm build --preset github_pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
